export default [
  'Spiderman',
  'Action',
  'Batman',
  'Tarantino',
  'DiCaprio',
  'Spielberg',
  'Scorsese',
  'Godfather',
  'Avengers',
  'Christopher Nolan',
  'Inception',
  'Fight Club',
  'Forrest Gump',
  'Tom Hanks',
  'Interstellar',
  'Gladiator',
  'Thriller',
  'Drama',
  'Sci-Fi',
  'Comedy',
];