// Movie actions
export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_ERROR = 'LOAD_MOVIES_ERROR';
export const SEARCH_AND_SORT = 'SEARCH_AND_SORT';

// DisplayMovie actions
export const SET_DISPLAY_MOVIE = 'SET_DISPLAY_MOVIE';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// User actions
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';

export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS';
export const REMOVE_MOVIE_ERROR = 'REMOVE_MOVIE_ERROR';
export const GET_MOVIELIST = 'GET_MOVIELIST';
export const GET_MOVIELIST_ERROR = 'GET_MOVIELIST_ERROR';
